version: "3.9"

networks:
  dt_money_network:
    driver: bridge

services:
  nginx:
    build: ./nginx/
    container_name: 'dt_money-nginx'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./dt_money/static:/var/www/static/
      - ./dt_money/staticfiles/admin:/var/www/static/admin/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dt_money_network
    depends_on:
      - dtmoney

  dt_money-db:
    image: postgres
    container_name: 'dt_money-database'
    volumes:
      - ./data/db/dt_money_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dt_money_network

  dtmoney:
    build: './dt_money/'
    container_name: "dtmoney-container"
    command: bash -c "python manage.py collectstatic --noinput  
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn dt_money.wsgi --bind 0.0.0.0 --reload"
    volumes:
      - ./dt_money:/dt_money/
    networks:
      - dt_money_network
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_API_KEY=${DJANGO_API_KEY}
    depends_on:
      - dt_money-db