# Generated by Django 4.1 on 2022-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
